// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data.Data;

#nullable disable

namespace Shop.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250330055013_AddNEWmigrationfk")]
    partial class AddNEWmigrationfk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Mecha"
                        });
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Eiichiro Oda",
                            CategoryId = 3,
                            Description = "Follow Monkey D. Luffy and his pirate crew in their quest to find the greatest treasure, the One Piece, and become the Pirate King.\r\n\r\nJoin them as they face formidable foes and uncover the mysteries of the Grand Line.",
                            ISBN = "SWD9999001",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "One Piece"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Chugong",
                            CategoryId = 1,
                            Description = "In a world where hunters with various magical powers battle deadly monsters, Sung Jin-Woo, the weakest of all hunters, finds himself in a never-ending struggle for survival.\r\n\r\nAs he discovers a mysterious power, he begins to level up beyond imagination.",
                            ISBN = "CAW777777701",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Solo Leveling"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Akira Toriyama",
                            CategoryId = 2,
                            Description = "The adventures of Goku and his friends as they defend the Earth from an assortment of villains ranging from intergalactic space fighters and conquerors, unnaturally powerful androids, and nearly indestructible creatures.\r\n\r\nWitness epic battles and transformations that push the limits of power.",
                            ISBN = "RITO5555501",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Dragon Ball Z"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Masashi Kishimoto",
                            CategoryId = 7,
                            Description = "Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the village's leader and strongest ninja.\r\n\r\nFollow his journey as he overcomes challenges and forms bonds with his friends.",
                            ISBN = "WS3333333301",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Naruto"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Yūki Tabata",
                            CategoryId = 2,
                            Description = "Asta, a young boy born without any magic power, aims to become the Wizard King to prove his strength and protect his kingdom.\r\n\r\nWith determination and hard work, he faces numerous magical threats.",
                            ISBN = "SOTJ1111111101",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Black Clover"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Tite Kubo",
                            CategoryId = 5,
                            Description = "Ichigo Kurosaki, a teenager with the ability to see ghosts, gains the powers of a Soul Reaper and must protect the living world from evil spirits and guide the souls of the deceased to the afterlife.\r\n\r\nExperience his battles and growth as a protector of both worlds.",
                            ISBN = "FOT000000001",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "Bleach"
                        });
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.HasOne("Shop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
